# ===================================================================
# DATABASE CONNECTION CONFIGURATION
# ===================================================================

# The 'url' tells Spring Boot EXACTLY where to find the database server.
# - 'jdbc:mysql://' is the protocol (the language used to talk to MySQL).
# - 'localhost:3306' means the database is running right here on this computer on port 3306 (our Docker container).
# - '/job_tracker_db' is the name of the specific database inside MySQL we want to open.
# - 'allowPublicKeyRetrieval=true&useSSL=false' are security settings required for local development.
spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker_db?allowPublicKeyRetrieval=true&useSSL=false

# The administrative username we configured inside our docker-compose.yml file.
spring.datasource.username=root

# FIX: '${DB_PASSWORD:rootpassword}' means:
# 1. Look for a system environment variable named DB_PASSWORD.
# 2. If it exists, use its hidden value securely.
# 3. If it doesn't exist, fall back to 'rootpassword' ONLY for local docker development safety.
spring.datasource.password=${DB_PASSWORD:rootpassword}


# ===================================================================
# HIBERNATE / JPA CONFIGURATION (THE TRANSLATOR LAYER)
# ===================================================================

# 'ddl-auto=update' is incredibly powerful. It tells Spring Boot to look at our 
# Java classes (like JobApplication.java) and automatically build or update the 
# database tables in MySQL to match them every time the application starts up.
spring.jpa.hibernate.ddl-auto=update

# 'show-sql=true' tells Spring Boot to print the exact raw SQL database commands 
# into our terminal logs. This lets us watch Hibernate actively talking to MySQL.
spring.jpa.show-sql=true


# ===================================================================
# REDIS CACHE CONFIGURATION
# ===================================================================

# Tells Spring Boot where to find the running Redis instance (our Docker container)
spring.data.redis.host=localhost

# The standard default network port that Redis listens on
spring.data.redis.port=6379

# ===================================================================
# APACHE KAFKA PRODUCER CONFIGURATION
# ===================================================================

# Tells our application where to find our running Kafka broker container (Port 9092)
spring.kafka.bootstrap-servers=localhost:9092

# Defines how Kafka should format the messages it sends over the network.
# Keys will be plain text Strings, and Values will be translated into clean JSON text strings.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer