# ===================================================================
# DATABASE CONNECTION CONFIGURATION (THE REPORTING DATA LAYER)
# ===================================================================

# Tells this service to connect to the exact same MySQL container on port 3306.
spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=rootpassword

# Tells Hibernate to automatically build our operational reporting tables.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===================================================================
# APACHE KAFKA CONFIGURATION (THE MESSAGING BUS)
# ===================================================================

# Tells our application where to find our running Kafka broker container in Docker.
spring.kafka.bootstrap-servers=localhost:9092

# Assigns this microservice to a unique Consumer Group. 
# This ensures that multiple instances of our analytics tool can share the data load.
spring.kafka.consumer.group-id=analytics-group

# Tells our consumer to read a queue from the absolute beginning if it encounters a brand-new topic.
spring.kafka.consumer.auto-offset-reset=earliest